---
title: "Resources"
---

## Required Textbooks

```{r}
#| echo: false
#| warning: false
#| message: false

package.list <- c('gt', 'tidyverse')

## Installing them if they aren't already on the computer
new.packages <- package.list[!(package.list %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages, repos = "http://cran.us.r-project.org")

## And loading them
for(i in package.list){library(i, character.only = T)}

tibble(
  title = c("<a href = 'pdfs/TeamScienceFieldGuide.pdf'>Collaboration and Team Science: A Field Guide</a>",
            '<a href = "https://brenebrown.com/book/dare-to-lead/">Dare to Lead</a>',
            "<a href = 'pdfs/DTLWorkbook.pdf'>Dare to Lead Workbook</a>")
) %>%
  mutate(title = map(title, gt::html)) %>%
  gt()  %>%
  tab_options(table.font.size = 30,
              table.font.weight = 'lighter',
              column_labels.hidden = TRUE,
              table.align='left',
              table.border.top.style = "hidden",
              table.border.bottom.style = "hidden") %>%
  cols_align(align = c("left"),
  columns = everything()) %>%
   tab_style(
    style = cell_borders(
      sides = c("top", "bottom"),
      color = NULL,
      weight = px(1.5),
      style = "solid"
    ),
    locations = cells_body(
      columns = everything(),
      rows = everything()
    )
  )

```

```{r}
#| include: false
#| eval: false


#### [Collaboration and Team Science: A Field Guide](https://brdo.berkeley.edu/sites/default/files/teamscience_fieldguide_reduced.pdf){target="_blank"} ("Team Science Field Guide" in weekly readings)

#### Dare to Lead (hard copy provided to all students; "DtL" in weekly readings)

#### [Dare to Lead Workbook](\pdfs\DTLWorkbook.pdf){target="_blank"} ("DtL Workbook" in weekly assignments)
```

## Weekly Reading and Assignments

Readings and assignments are provided in this schedule on the day they're **assigned**. Unless otherwise noted, reading should be done and assignments completed by the following class period.

```{r}
#| echo: false
#| warning: false
#| message: false

tibble(
  Week = c("1", "",
           "2", "",
           "3", "",
           "4", "",
           "5", "",
           "6", "",
           '7', '',
           '8', '',
           '9', '',
           '10', '',
           '11', ''),
  Day = c("8/29", "8/31",
          "9/5", "9/7",
          "9/12", "9/14",
          '9/19', '9/21',
          '9/26', '9/28',
          '10/3', '10/5',
          '10/10','10/12',
          '10/17', '10/19',
          '10/24', '10/26',
          '10/31', '11/2',
          '11/7', '11/9'),
  Reading = c("<a href = '/pdfs/CheruvelilSoranno2018.pdf'>Cheruvelil & Soranno 2018</a>_n<a href = '/pdfs/DtLIntrop1s1.pdf'>DtL: Intro and Part 1, Section 1_n(pages 1-43)</a>",
              "",
              "Team Science Field Guide: pages iii-3_n <a href = '/pdfs/Cheruvelil2014.pdf'>Cheruvelil et al. 2014</a>",
              "",
              "DtL: Part 1, Sections 2-3_n(pages 44-177)",
              "Team Science Field Guide: pages 5-19",
              "Team Science Field Guide: pages 25-34",
              "Team Science Field Guide: pages 21-24_n 39-44",
              "Team Science Field Guide: pages 45-50",
              "<a href = 'https://www.nature.com/articles/d41586-021-01573-z'>We need to talk</a>_n<a href = '/pdfs/Conflict_energy.pdf'>The seven levels of energy</a>",
              '<a href = "https://www.nature.com/articles/d41586-021-01635-2">Communities, COVID, and credit: the state of science collaborations</a>',
              'DtL: Part 1, Sections 4-5 & Part 2_n(pages 118-217)', 
              '', '',
              '<a href = "https://www.ted.com/talks/tom_wujec_got_a_wicked_problem_first_tell_me_how_you_make_toast">Tell me how you make toast TED Talk</a>', '',
              '<a href = "https://podcasts.apple.com/us/podcast/coaching-for-leaders/id458827716?i=1000363385074">How to Make Deep Work Happen</a>_n<a href = "https://www.ted.com/talks/cindy_solomon_5_tips_for_dealing_with_meeting_overload">5 Tips for Meeting Overload</a>', '<a href = "http://www.paulgraham.com/makersschedule.html">Makers Schedule, Managers Schedule</a>_n<a href = "https://www.youtube.com/watch?si=_FiWodbz_HxanfIk&v=YCYBbmtcRNA&feature=youtu.be">Optional: Why Track Team Time?</a>',
              '', '',
              '<a href = "https://24slides.com/presentbetter/simple-group-presentation-tips">Simple Group Presentation Tips</a>_n<a href = "https://thepotentiality.com/six-tips-for-a-successful-collaboration-when-giving-a-speech/">Six Tips for Collaborative Presenting</a>', ''),
  Assignment = c("DtL Workbook:_nSection 1, Exercise 1_nSection 1, Exercise 2", 
                 "<a href = '/pdfs/ElevatorPitches.pdf'>Elevator Pitch</a>",
                 "<a href = 'https://docs.google.com/forms/d/e/1FAIpQLSenhpqyKnW2N0Ih3NeVyc0AkxIy6o9iVXv8Cdw3UVnOIAOEqg/viewform'>Cheruvelil Reading Questions</a>",
                 "<a href = 'https://docs.google.com/spreadsheets/d/1x8N-3SaOOTeJA0_wY6xXIQEvsbxuRZ944wIiiJbp3-0/edit#gid=259107515'>True Colors Assessment</a>",
                 'DtL Workbook:_nSection 2, Exercise 1_nSection 2, Exercise 4',
                 '<a href = "https://docs.google.com/forms/d/e/1FAIpQLScY8EtcrPqe0WgVPFOl-ONgyIhULFC9VaxqiGiAmjhNvtzaXA/viewform">Myers Briggs Assessment</a>', 
                 "<a href = 'https://docs.google.com/forms/d/e/1FAIpQLSc8FJNfNInGOwKIfPOjOioxsq5pXnSH9WnlbHNqXNntl4qoYQ/viewform'>Communication Reading Questions</a>", 
                 "<a href = 'https://docs.google.com/document/d/1cnAmBvaHmpFvtA9EIgVZYJwW3d6rOzFbsv8r819ML30/edit#heading=h.nj23sjpj5u97'>Team vision statements</a>_n Due 10/16/23",
                 "<a href = 'https://docs.google.com/forms/d/e/1FAIpQLSd0svPcJ1vvDBEjCZn-5G_21RWT2Pn_uvzEe2sBdV78J7l3Qw/viewform'>Effective Meetings Mini-Project</a>", 
                 "",
                 "", 
                 "<a href = 'https://canvas.nau.edu/courses/11749/assignments/284630'>DtL Workbook:_nSection 4,_nExercises 1,4,5,&6_n Section 5, Exercises 1&2</a>",
                 '', '<a href = "https://canvas.nau.edu/courses/11749/assignments/260814">Team Vision Statements/Collaborative Research Agreements (due 10/16)</a>',
                 '', '',
                 '<a href = "https://docs.google.com/forms/d/e/1FAIpQLScc5Ls0YvbYVhlbVyX0QUYDQyNvzxy7UH_5agD2Q9jUvT8nwQ/viewform">Burnout Check-In</a>', '<a href = "https://canvas.nau.edu/courses/11749/assignments/302742">Available to Promise</a>',
                 '<a href = "https://docs.google.com/forms/d/e/1FAIpQLSfXVbVyUM5yajIY3FVtbKgeqmFL0XuXwF-c_N9ZC-K_xIL1hg/viewform">Group Presentation Mini-Project</a>', '',
                 '', '')
) %>%
  mutate(Reading = str_replace_all(Reading, "_n", "<br>"),
         Assignment = str_replace_all(Assignment, "_n", "<br>")) %>% 
  mutate(Reading = map(Reading, gt::html),
         Assignment = map(Assignment, gt::html)) %>%
  gt() %>%
  tab_options(table.font.size = 20,
              column_labels.font.weight = 'bold',
              column_labels.font.size = 20) %>%
  opt_horizontal_padding(scale = 3) %>% 
  cols_align(align = c("left"),
  columns = everything() )%>%
  fmt_markdown(columns = TRUE)
  

```
